services:
  localstack:
    image: localstack/localstack:latest
    container_name: datacite_localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      localstack_network:
        ipv4_address: 10.0.2.20

networks:
  localstack_network:
    name: localstack_network
    ipam:
      config:
        - subnet: 10.0.2.0/24
